### ISSUE TITLE
Wrong CSS Output instead of clamp values

### ISSUE THREAD

**Issue by razaanstha** [barvian/fluid-tailwind#2]
I have my classname `~pb-20/40` but its returning the CSS output like this for all fluid-tailwind classname syntax: 
```
.\~pb-20\/40 {
  padding-bottom: /* fluid from 5rem at 640px to 10rem at 1920px */;
}
```
![image](https://github.com/barvian/fluid-tailwind/assets/38215032/422e83c9-3fb2-4c66-ae04-317f2a503c3d)

I have followed the same installation guide from the [installation](https://fluid.tw/#installation) section but its not showing the correct CSS ouput. 🤔

**Comment by barvian** [comment]
Thanks for posting! It looks like you're using `px` for screen widths and `rem`s for padding. Due to CSS restrictions, [all units have to be the same](https://fluid.tw/#all-lengths-must-have-the-same-unit) for fluid clamps. If you're using Tailwind's default screens, you can check out the 4th step in the [installation instructions](https://fluid.tw/#installation). Otherwise, you'd have to convert either your screens to `rem`s or your padding values to `px`.

**Comment by razaanstha** [comment]
Aha, you were right I didn't check the documentation well :)
Thank you for your help!
