### ISSUE TITLE
Warning will be thrown for .5 values

### ISSUE THREAD

**Issue by mdillgen** [barvian/fluid-tailwind#27]
_First of all, thank you!!! It is such a great plugin!_ 

The plugin issues a “Missing end value” warning if decimal values are used, e.g. ~my-1.5/4
In some occasions “Start and end values are both 0.25rem”. Both is not true and everything is working as expected.

Reproduction repo:
https://github.com/mdillgen/next15.git

**Comment by barvian** [comment]
Thanks for the repo! Looking into this

**Comment by mdillgen** [comment]
@barvian Just wanted to add FYI: I have used next15rc for the repo but warnings also appear on latest (next 14.2.3).

**Comment by barvian** [comment]
Alright so it looks like this was related to a known Tailwind limitation (see tailwindlabs/tailwindcss#9354). I just released v0.3.9 that now outputs all errors as CSS comments instead of console warnings, which should address this and probably improves the DX overall (see i.e. #20). Here's the [updated portion of the docs](https://fluid.tw/#troubleshooting), if you're interested.

Thanks for reporting! Feel free to leave another comment if you have any feedback

**Comment by mdillgen** [comment]
Thanks for the quick reaction!
