### ISSUE TITLE
Not working with width utilities, am I doing something wrong? 

### ISSUE THREAD

**Issue by rhysmatthew** [barvian/fluid-tailwind#3]
Hey, great plugin by the way, loving it so far! 

Working perfectly for fonts but when I thought I'd try using for widths on a specific component, it doesn't seem to generate anything.

I do have custom screens set to px so I can't really import the default ones in rem.

I've tried using px to match the value types but still no luck. Variants I've tried:

```
~/md:~w-[200px]/[300px]
~/md:~w-5/10
```

If I take the breakpoint part off, I get this generated in the CSS output

```
.\~w-5\/10 {
    width: /* not fluid from 1.25rem at 25.875rem to 2.5rem at 100rem: Breakpoint and value units don't match */;
}
```

**Comment by rhysmatthew** [comment]
Also, I have a postcss PX to rem package in place, so all my font sizes end up as rems fyi.

**Comment by barvian** [comment]
Thanks for the info! I think the problem with `~/md:~w-5/10` and `~w-5/10` is that the default widths in Tailwind are in `rem`, while your screens are in `px`. The output comment you posted might be caused by the px-to-rem plugin transforming the values inside the CSS comment; I was able to reproduce that with [this px-to-rem plugin](https://www.npmjs.com/package/postcss-pxtorem) and a `propList: ['*']` option. Is that similar to your setup?

The confusing part is that `~/md:~w-[200px]/[300px]` didn't work for you. I'm getting what appears to be a correct output for that (after a px-to-rem conversion):
```css
.\~\/md\:\~w-\[200px\]\/\[300px\] {
    width: clamp(12.5rem, 5.19063rem + 28.25vw, 18.75rem) /* fluid from 12.5rem at 25.875rem to 18.75rem at 48rem */;
}
```

Would you be able to post the output you get for that class? If it doesn't output anything, would you be able to check the console for a warning?

**Comment by rhysmatthew** [comment]
Thanks, it does seem to be that plugin creating these bugs as you say. And yes that's the exact plugin I'm using. 

Oddly that class is outputting now without issues, I can't explain why at this point. But ~/md:~w-[200px]/[300px] or ~w-[200px]/[300px] does output something like this with no errors: 

```
width: clamp(12.5rem, 6.73063rem + 12.02vw, 18.75rem);
```

I think we can safely say it's an issue with using a plugin like this, that also manipulates the values. It's just the case where I like to think in terms of px instead of rem so I use this tool all the time.

Maybe soon I'll try not using the pxtorem plugin and see how I get on.

**Comment by barvian** [comment]
Awesome, glad that one's working now!
